// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using voucherMicroservice.Data;

#nullable disable

namespace voucherMicroservice.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240827083217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("voucherMicroservice.Model.Floating", b =>
                {
                    b.Property<int>("h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("h_id"));

                    b.Property<decimal>("credit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("month_credit")
                        .HasColumnType("longtext");

                    b.Property<int>("pay_date")
                        .HasColumnType("int");

                    b.Property<string>("student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("user_update")
                        .HasColumnType("longtext");

                    b.HasKey("h_id");

                    b.ToTable("Floatings");
                });

            modelBuilder.Entity("voucherMicroservice.Model.PayHistory", b =>
                {
                    b.Property<int>("h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("h_id"));

                    b.Property<decimal>("credit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("debit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("month_credit")
                        .HasColumnType("longtext");

                    b.Property<int>("pay_date")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.Property<string>("seller")
                        .HasColumnType("longtext");

                    b.Property<string>("student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("user_update")
                        .HasColumnType("longtext");

                    b.HasKey("h_id");

                    b.ToTable("PayHistories");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Seller", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("s_id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("date_update")
                        .HasColumnType("int");

                    b.Property<string>("firstTime")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("s_name")
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.HasKey("s_id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("voucherMicroservice.Model.StaffList", b =>
                {
                    b.Property<int>("req_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("req_id"));

                    b.Property<string>("employ_status")
                        .HasColumnType("longtext");

                    b.Property<string>("firstTime")
                        .HasColumnType("longtext");

                    b.Property<string>("icnumber")
                        .HasColumnType("longtext");

                    b.Property<string>("job_grade")
                        .HasColumnType("longtext");

                    b.Property<string>("lvl_access")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("phone_no")
                        .HasColumnType("longtext");

                    b.Property<string>("s_campus")
                        .HasColumnType("longtext");

                    b.Property<string>("s_dept")
                        .HasColumnType("longtext");

                    b.Property<string>("s_designation")
                        .HasColumnType("longtext");

                    b.Property<string>("s_email")
                        .HasColumnType("longtext");

                    b.Property<int>("s_hiredate")
                        .HasColumnType("int");

                    b.Property<string>("s_location")
                        .HasColumnType("longtext");

                    b.Property<string>("s_name")
                        .HasColumnType("longtext");

                    b.Property<string>("s_nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("s_position")
                        .HasColumnType("longtext");

                    b.Property<string>("s_section")
                        .HasColumnType("longtext");

                    b.Property<string>("s_supervisor")
                        .HasColumnType("longtext");

                    b.Property<string>("s_supervisor2")
                        .HasColumnType("longtext");

                    b.Property<string>("staff_id")
                        .HasColumnType("longtext");

                    b.Property<string>("staff_status")
                        .HasColumnType("longtext");

                    b.Property<string>("teach_status")
                        .HasColumnType("longtext");

                    b.HasKey("req_id");

                    b.ToTable("StaffLists");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("batch")
                        .HasColumnType("longtext");

                    b.Property<string>("campus")
                        .HasColumnType("longtext");

                    b.Property<int>("complete_date")
                        .HasColumnType("int");

                    b.Property<string>("course_code")
                        .HasColumnType("longtext");

                    b.Property<int>("date_update")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("firsTime")
                        .HasColumnType("longtext");

                    b.Property<string>("intake")
                        .HasColumnType("longtext");

                    b.Property<string>("month_credit")
                        .HasColumnType("longtext");

                    b.Property<string>("nric")
                        .HasColumnType("longtext");

                    b.Property<int>("register_date")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<string>("student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("student_name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
