// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using voucherMicroservice.Data;

#nullable disable

namespace voucherMicroservice.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("voucherMicroservice.Model.AuthLog", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ip_address")
                        .HasColumnType("longtext");

                    b.Property<string>("session_id")
                        .HasColumnType("longtext");

                    b.Property<int>("timestamp")
                        .HasColumnType("int");

                    b.Property<string>("user_agent")
                        .HasColumnType("longtext");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("auth_log");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Floating", b =>
                {
                    b.Property<int>("h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("h_id"));

                    b.Property<decimal>("credit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("month_credit")
                        .HasColumnType("longtext");

                    b.Property<int>("pay_date")
                        .HasColumnType("int");

                    b.Property<string>("student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("user_update")
                        .HasColumnType("longtext");

                    b.HasKey("h_id");

                    b.ToTable("floating");
                });

            modelBuilder.Entity("voucherMicroservice.Model.PayHistory", b =>
                {
                    b.Property<int>("h_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("h_id"));

                    b.Property<decimal?>("credit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("debit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("month_credit")
                        .HasColumnType("longtext");

                    b.Property<int>("pay_date")
                        .HasColumnType("int");

                    b.Property<string>("remark")
                        .HasColumnType("longtext");

                    b.Property<string>("seller")
                        .HasColumnType("longtext");

                    b.Property<string>("student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("transaction_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_update")
                        .HasColumnType("longtext");

                    b.HasKey("h_id");

                    b.ToTable("payhistory");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Permission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("voucherMicroservice.Model.RolePermission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("granted_at")
                        .HasColumnType("bigint");

                    b.Property<string>("granted_by")
                        .HasColumnType("longtext");

                    b.Property<string>("permission_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Seller", b =>
                {
                    b.Property<int>("s_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("s_id"));

                    b.Property<decimal?>("balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("date_update")
                        .HasColumnType("int");

                    b.Property<string>("firstTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("last_password_change")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("s_id");

                    b.ToTable("seller");
                });

            modelBuilder.Entity("voucherMicroservice.Model.SellerBalanceSnapshot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("created_at")
                        .HasColumnType("int");

                    b.Property<long>("cutover_date")
                        .HasColumnType("bigint");

                    b.Property<decimal>("legacy_balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("seller_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("seller_balance_snapshot");
                });

            modelBuilder.Entity("voucherMicroservice.Model.StaffList", b =>
                {
                    b.Property<int>("req_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("req_id"));

                    b.Property<int>("access_level")
                        .HasColumnType("int");

                    b.Property<string>("employ_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("icnumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("job_grade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("last_password_change")
                        .HasColumnType("int");

                    b.Property<string>("lvl_access")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone_no")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_campus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_dept")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("s_hiredate")
                        .HasColumnType("int");

                    b.Property<string>("s_location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_section")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_supervisor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("s_supervisor2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("staff_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("staff_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("teach_status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("req_id");

                    b.ToTable("stafflist");
                });

            modelBuilder.Entity("voucherMicroservice.Model.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("batch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("campus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("complete_date")
                        .HasColumnType("int");

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("date_update")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("firstTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("intake")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("last_password_change")
                        .HasColumnType("int");

                    b.Property<string>("month_credit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nric")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("register_date")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("student_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("student_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("student");
                });

            modelBuilder.Entity("voucherMicroservice.Model.TokenBlacklist", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("expires_at")
                        .HasColumnType("bigint");

                    b.Property<string>("jti")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("revoked_at")
                        .HasColumnType("bigint");

                    b.Property<string>("user_id")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("token_blacklist");
                });

            modelBuilder.Entity("voucherMicroservice.Model.UserPermission", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("is_granted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("permission_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("set_at")
                        .HasColumnType("bigint");

                    b.Property<string>("set_by")
                        .HasColumnType("longtext");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.ToTable("user_permissions");
                });

            modelBuilder.Entity("voucherMicroservice.Model.RolePermission", b =>
                {
                    b.HasOne("voucherMicroservice.Model.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("voucherMicroservice.Model.UserPermission", b =>
                {
                    b.HasOne("voucherMicroservice.Model.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });
#pragma warning restore 612, 618
        }
    }
}
