using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using voucherMicroservice.Data;
using voucherMicroservice.Model;

namespace voucherMicroservice.Services
{
    public class UsermanagementService : IUsermanagementService
    {
        private readonly DataContext dataContext;
        private readonly IPasswordService _passwordService;
        private readonly IEmailService _emailService;  // Optional: for sending emails
        private readonly ILogger<UsermanagementService> _logger;


        public UsermanagementService(DataContext dataContext, IPasswordService passwordService, IEmailService emailService, ILogger<UsermanagementService> logger)
        {
            this.dataContext = dataContext;
            this._passwordService = passwordService;
            this._emailService = emailService;
            this._logger = logger;
        }

        public async Task<ResponseCustomModel<string>> CreateStudent(CreateStudent studentRequest)
        {
            using var transaction = await dataContext.Database.BeginTransactionAsync();
            var result = new ResponseCustomModel<string>();
            try
            {
                var existingStudent = await dataContext.student.AnyAsync(s => s.student_id == studentRequest.student_id.Trim());

                if (existingStudent)
                {
                    return new ResponseCustomModel<string>
                    {
                        Success = false,
                        Message = "Student ID already exists!",
                    };
                }

                var emailExist = await dataContext.student.AnyAsync(s => s.email == studentRequest.email);
                if (emailExist)
                {
                    return new ResponseCustomModel<string>
                    {
                        Success = false,
                        Message = "Email already exists!"
                    };
                }
                string autoGeneratedPassword = "Skills@" + studentRequest.nric;

                string temporaryPassword = _passwordService.GenerateTemporaryPassword();
                string hashedPassword = _passwordService.HashPassword(autoGeneratedPassword);

                int currentTimestamp = (int)DateTimeOffset.UtcNow.ToUnixTimeSeconds();

                var newStudent = new Student
                {
                    student_id = studentRequest.student_id,
                    student_name = studentRequest.student_name,
                    nric = studentRequest.nric,
                    password = hashedPassword,
                    email = studentRequest.email,
                    register_date = studentRequest.register_date,
                    complete_date = studentRequest.complete_date,
                    intake = studentRequest.intake,
                    course_code = studentRequest.course_code,
                    balance = 0,
                    month_credit = "No data",
                    campus = studentRequest.campus,
                    // batch = studentRequest.batch,
                    firstTime = "Yes",
                    status = "Yes",
                    must_change_password = true,
                    last_password_change = 0,
                    date_update = currentTimestamp
                };

                await dataContext.student.AddAsync(newStudent);
                await dataContext.SaveChangesAsync();

                await transaction.CommitAsync();
                result.Success = true;
                result.Message = "Student created succesfully.";


                return result;
            }
            catch (System.Exception)
            {
                await transaction.RollbackAsync();
                throw;
            }
        }

        public async Task<ResponseCustomModel<string>> CreateStudentBulk(List<CreateStudent> students)
        {
            // using var transaction = await dataContext.Database.BeginTransactionAsync();

            int ct = (int)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            var response = new ResponseCustomModel<string>();

            foreach (var request in students)
            {
                var result = await CreateStudent(request);
                response.Success = result.Success;
                response.Message = result.Message;
            }

            return response;


        }

        public async Task<ResponseCustomModel<Student>> GetStudentById(string studentId)
        {
            var studentData = await dataContext.student.Where(s => s.student_id == studentId).FirstOrDefaultAsync();
            var response = new ResponseCustomModel<Student>();

            if (!studentData.Equals(0))
            {
                response.Success = false;
                response.Message = "Student not found";
            }

            response.Success = true;
            response.Count = 1;
            response.Message = $"Found student for student id: {studentId}";
            response.Data = studentData;

            return response;
        }

        public async Task<ResponseCustomModel<string>> UpdateStudent(UpdateStudent student, string studentId)
        {
            using var transactions = await dataContext.Database.BeginTransactionAsync();
            var response = new ResponseCustomModel<string>();
            int ct = (int)DateTimeOffset.UtcNow.ToUnixTimeSeconds();

            var checkStudent = await dataContext.student.AnyAsync(x => x.student_id == studentId);
            if (!checkStudent)
            {
                response.Success = false;
                response.Message = "Student id wrong or not found!";
                return response;
            }
            else
            {
                try
                {
                    var studentData = await dataContext.student.Where(s => s.student_id == studentId)
                    .ExecuteUpdateAsync(s => s
                    .SetProperty(s => s.student_name, s => student.student_name)
                    .SetProperty(s => s.balance, student.balance)
                    // .SetProperty(s => s.batch, s => student.batch)
                    .SetProperty(s => s.campus, s => student.campus)
                    .SetProperty(s => s.complete_date, s => student.complete_date)
                    .SetProperty(s => s.register_date, s => student.register_date)
                    .SetProperty(s => s.course_code, s => student.course_code)
                    .SetProperty(s => s.date_update, s => ct)
                    .SetProperty(s => s.email, s => student.email)
                    .SetProperty(s => s.firstTime, s => student.firstTime)
                    .SetProperty(s => s.status, s => student.status)
                    .SetProperty(s => s.intake, s => student.intake)
                    .SetProperty(s => s.last_password_change, s => student.last_password_change)
                    );


                    response.Success = true;
                    response.Message = "Student data updated successfully";

                    await dataContext.SaveChangesAsync();
                    await transactions.CommitAsync();

                    return response;
                }
                catch (System.Exception ex)
                {
                    response.Message = ex.Message.ToString();
                    response.Success = false;
                    await transactions.RollbackAsync();
                    return response;
                    throw;
                }
            }

        }

        public async Task<ResponseCustomModel<string>> DeleteStudent(string studentId)
        {
            using var transaction = await dataContext.Database.BeginTransactionAsync();

            var response = new ResponseCustomModel<string>();

            var checkExist = await dataContext.student.AnyAsync(x => x.student_id == studentId);

            if (!checkExist)
            {
                response.Message = "Student not found or wrong id!";
                response.Success = false;
            }
            else
            {
                try
                {
                    await dataContext.student.Where(s => s.student_id == studentId).ExecuteDeleteAsync();
                    await dataContext.SaveChangesAsync();
                    await transaction.CommitAsync();
                    response.Success = true;
                    response.Message = "Student deleted successfully!";

                }
                catch (System.Exception ex)
                {
                    await transaction.RollbackAsync();
                    response.Success = false;
                    response.Message = ex.Message.ToString();
                    return response;
                    throw;
                }

            }

            return response;
        }

        public async Task<ResponseCustomModel<string>> WrongCreditBySeller(string studentId, decimal wrongamount, string sellerName, decimal exactamount)
        {
            var response = new ResponseCustomModel<string>();
            using var transaction = await dataContext.Database.BeginTransactionAsync();
            int ct = (int)DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            var groupId = Guid.NewGuid().ToString();

            try
            {
                var checkExist = await dataContext.student.AnyAsync(x => x.student_id == studentId);
                if (!checkExist)
                {
                    response.Message = "Student not found or wrong id!";
                    response.Success = false;
                    return response;
                }
                var checkseller = await dataContext.seller.AnyAsync(x => x.s_name == sellerName);
                if (!checkseller)
                {
                    response.Message = "Seller not found or wrong name!";
                    response.Success = false;
                    return response;
                }

                var studentData = await dataContext.student.Where(s => s.student_id == studentId)
                    .ExecuteUpdateAsync(s => s
                    .SetProperty(s => s.balance, s => s.balance + wrongamount - exactamount)
                    .SetProperty(s => s.date_update, s => ct)
                    );

                var sellerData = await dataContext.seller.Where(s => s.s_name == sellerName)
                    .ExecuteUpdateAsync(s => s
                    .SetProperty(s => s.balance, s => s.balance - wrongamount + exactamount)
                    .SetProperty(s => s.date_update, s => ct)
                    );

                var histories = new List<PayHistory>
                    {
                        new PayHistory
                        {
                            transaction_id = groupId,
                            student_id = studentId,
                            seller = sellerName,
                            debit = exactamount,
                            credit = 0,
                            remark = "WRONG_CREDIT_BY_SELLER",
                            pay_date = ct,
                            user_update = sellerName,
                            month_credit = string.Empty
                        },
                        new PayHistory
                        {
                            transaction_id = groupId,
                            student_id = studentId,
                            seller = sellerName,
                            debit = 0,
                            credit = exactamount,
                            remark = "CORRECT_CREDIT_BY_SELLER",
                            pay_date = ct,
                            user_update = sellerName,
                            month_credit = string.Empty
                        }
                    };
                await dataContext.payhistory.AddRangeAsync(histories);
                await dataContext.SaveChangesAsync();
                await transaction.CommitAsync();
                response.Success = true;
                response.Message = "Wrong credit corrected successfully!";


                return response;
            }
            catch (System.Exception e)
            {
                await transaction.RollbackAsync();

                response.Success = false;
                response.Message = e.Message.ToString();
                return response;
                throw;
            }


        }
    }
}